// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackgroundSelection } from './BackgroundSelection';
import type { CachePaths } from './CachePaths';
import type { CustomBackground } from './CustomBackground';
import type { LibrarySource } from './LibrarySource';
import type { SongSort } from './SongSort';

export type AppConfig = {
  data_path: string | null;
  cache_paths: CachePaths | null;
  /**
   * Deprecated. Kept for one-shot migration into `library_source`; never
   * written by code that has been through `with_defaults`.
   */
  last_folder: string | null;
  library_source: LibrarySource | null;
  last_theme: number | null;
  custom_backgrounds: Array<CustomBackground>;
  last_background: BackgroundSelection | null;
  guide_volume: number | null;
  master_volume: number | null;
  fullscreen: boolean | null;
  playback_mode: string | null;
  dark_mode: boolean | null;
  mic_active: boolean | null;
  /**
   * `serde(alias = "mic_mirroring")` keeps configs written by builds that
   * called this feature "mic mirroring" loading without a manual migration;
   * the next `save` rewrites them under the new name.
   */
  mic_monitoring: boolean | null;
  mic_monitor_gain: number | null;
  mic_latency_compensation_sec: number | null;
  preferred_mic: string | null;
  whisper_model: string | null;
  beam_size: number | null;
  batch_size: number | null;
  last_video_flavor: number | null;
  lyrics_vertical_position: string | null;
  lyrics_horizontal_position: string | null;
  lyrics_scale: number | null;
  pitch_graph_scale: number | null;
  lyrics_romanization_mode: string | null;
  separator: string | null;
  asr_engine: string | null;
  align_backend: string | null;
  vocal_detection_threshold_pct: number | null;
  auto_analyze: boolean | null;
  /**
   * Audio codec used when exporting songs to `.nge` bundles: `"none"`
   * (keep stems as-is, lossless), `"opus128"`, or `"opus96"` (re-encode to
   * Opus at that bitrate to shrink bundles). Defaults to `"none"`.
   */
  export_audio_codec: string | null;
  /**
   * Hosts trusted to download from via the `nightingale://` deep link without
   * a confirmation prompt. Any other host prompts the user first. Empty/None
   * means every download is confirmed.
   */
  deep_link_allowed_hosts: Array<string> | null;
  song_list_view: string | null;
  song_list_sort: Array<SongSort> | null;
  language_overrides: { [key in string]: string } | null;
};
