// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of [`reconcile_cache`], scoped to this library: `matched` rows had
 * a transcript in the cache, of which `updated` were marked analyzed and
 * `skipped` were left alone because the entry is incomplete.
 */
export type CacheReconcileSummary = { matched: number; updated: number; skipped: number };
