// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LibraryMenuItem = {
  value: string;
  label: string;
  analysedCount: bigint;
  queuedCount: bigint;
  analysingCount: bigint;
  count: bigint;
  /**
   * Nesting level of a folder item below the library root (0 = top level).
   */
  depth?: number;
};
