// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryMenuItem } from "./LibraryMenuItem";

export type LibraryMenuItems = {
  hot: Array<LibraryMenuItem>;
  no_metadata: Array<LibraryMenuItem>;
  artists: Array<LibraryMenuItem>;
  albums: Array<LibraryMenuItem>;
  playlists: Array<LibraryMenuItem>;
  folders: Array<LibraryMenuItem>;
};
