// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LibraryMenuFilters = {
  artist: string | null;
  album: string | null;
  playlist: string | null;
  query: string | null;
  status: string | null;
  transcript_source: string | null;
  search: string | null;
  /**
   * Folder path prefix (ending in a separator) from a folder menu item.
   */
  folder: string | null;
};
