// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Start and end of a lyric line, in seconds on the original-tempo timeline.
 */
export type LineWindow = { start: number; end: number };
