// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineWindow } from "./LineWindow";

export type LyricsFile = {
  lines: Array<string>;
  /**
   * Per-line time windows from line-timed LRC, parallel to `lines`. When
   * present, alignment only places each line's words inside its window.
   */
  windows?: Array<LineWindow>;
};
