// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SidecarLrcKind } from './SidecarLrcKind';

/**
 * An `.lrc` / `.elrc` file found next to a local song's audio. `file_name` is
 * the bare basename so the UI can say which file was picked without ever
 * receiving a directory.
 */
export type SidecarLrc = { text: string; file_name: string; kind: SidecarLrcKind };
